module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- 
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "buttonA.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 64, y = 192, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonA_over.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 64, y = 128, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonB.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 0, y = 192, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonB_over.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 0, y = 128, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonLeft.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 64, y = 64, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonLeft_over.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 0, y = 64, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonRight.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 64, y = 0, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "buttonRight_over.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 0, y = 0, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
    return sheet
end

